spring:
  datasource:
    url: jdbc:mysql://localhost:3306/toe?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true
    username: root
    password: Xqf123123

server:
  port: 7777

flyway:
  enabled: false

security:
  ignore: '/**'