spring:
  datasource:
    url: jdbc:mysql://localhost:3306/toe?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true
    username: root
    password: Xqf123123

security:
  basic:
    enabled: false

server:
  port: 8888

flyway:
  enabled: true