ALTER TABLE `address`
DROP FOREIGN KEY `ADDRESS_USER`;
ALTER TABLE `address`
DROP INDEX `USER_ID_idx` ;

ALTER TABLE `order`
DROP FOREIGN KEY `ORDER_USER`;
ALTER TABLE `order`
DROP INDEX `ORDER_USER_idx` ;

ALTER TABLE `order`
CHANGE COLUMN `orderId` `orderId` INT(11) NOT NULL AUTO_INCREMENT COMMENT '订单主键' ;
