ALTER TABLE `order` 
DROP FOREIGN KEY `ORDER_USER`;
ALTER TABLE `order` 
CHANGE COLUMN `carrierId` `carrierId` INT(11) NULL COMMENT '派送员' ,
CHANGE COLUMN `description` `description` VARCHAR(45) NULL COMMENT '描述' ,
CHANGE COLUMN `status` `status` TINYINT(4) NOT NULL COMMENT '状态：0-新订单，1-已接单，2-送达' ,
ADD COLUMN `ownerId` INT(11) NOT NULL AFTER `orderId`,
ADD INDEX `ORDER_OWNER_idx` (`ownerId` ASC);
ALTER TABLE `order` 
ADD CONSTRAINT `ORDER_USER`
  FOREIGN KEY (`carrierId`)
  REFERENCES `user` (`userId`)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION,
ADD CONSTRAINT `ORDER_OWNER`
  FOREIGN KEY (`ownerId`)
  REFERENCES `user` (`userId`)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION;